### PR TITLE
feat(entity): humanize entity for console logs

### PR DESCRIPTION
**Pull request by smothers**
- expose entities in a js friendly way
- attach some helpful metadata for debugging

E.g.
Screen Shot 2020-12-11 at 3 30 32 PM

### CODE REVIEW

**Comment by smothers** [comment]
I'll save adding an `entity.toJSON()` function for later since that's less trivial and we have a separate task for db.toJSON. 

In the meantime, we could expose more of the entity API such as the `entity.keys()` and `entity.vals()` functions. The issue is that they would return EDN instead of JSON, at least for the time being. Once we have toJSON it will be easier to map everything toJSON. 

What `entity.keys()` would look like now
Screen Shot 2020-12-11 at 3 53 43 PM

@rubinovitz what do you think? I can see `entity.keys()` being good and bad. It would tell you what keys an entity has, but only that specific entity, not the keys that all entities of that type can have. Maybe it makes more sense to expose some higher-level DB analytics that tracks all the keys(attributes) in the DB before exposing this function and potentially confusing people.

**Comment by rubinovitz** [comment]
@smothers 

Super excited to use this soon!  Some comments below.
## Re: Naming
What is `_recentlyTouchedAttributes` referring to? The naming is a bit confusing to me. Is it only showing attributes you just used? I assumed we'd surface all the attributes of the given entity? 

I think re your DM it makes sense not to render the debugging objects on the first level so people don't mistakenly use them to grab data in the app. However, I am worried about people finding the data in that case. Maybe very clear naming would help? I wonder if something like `_InspectAttributes` would make it clear it's there for their debugging needs. I'm trying to think of the naming for anything with a similar use case, and it's eluding me. I got "inspect" from this [Jetbrains](https://www.jetbrains.com/help/rider/Inspecting_Variables.html) use case.


## Re: QA
It looks like this isn't passing the benchmarks/e2e test? Can we get this passing that first?

**Comment by rubinovitz** [comment]
Also, could you add this to the README as its own Debugging section or in API reference?

**Comment by smothers** [comment]
@rubinovitz tests are passing, ready for QA.

As for exposing all attributes that will have to wait until we have a toJSON() function. It would be super expensive to walk the relational tree for every entity, especially when it could be arbitrarily deep. With toJSON we can add arguments like depth so we only walk a reasonable amount of the tree, but you'll still have to call that function, you won't be able to log an entity and just see all of its attributes.

Re naming `_recentlyTouchedAttributes` made the most sense to me and it seems like you understood it too.

> Also, could you add this to the README as its own Debugging section or in API reference?

Let's revisit this in another PR. This PR should be self-explanatory given it's just the shape of the data that's been made more readable. When we add the toJSON function then we can explain how to use it for debugging.

**Comment by rubinovitz** [comment]
Can you explain what `_recentlyTouchedAttributes` is? It's unclear to me.

Re docs, it's not self explanatory to me, re the above.

**Review by rubinovitz — APPROVED** [review]
This is working for me when I run it with our new demo and I think you're right about waiting for the next iteration of this for the other things I mentioned.

**Pull request merged**
